import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import AuthProvider from "@/Context/AuthProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Green Nest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <div className="bg-green-100 shadow-sm sticky top-0 z-50">
              <Navbar></Navbar>
            </div>
            <div className="flex-1">{children}</div>
            <div className="bg-gray-300 mt-15">
              <Footer></Footer>
            </div>
          </div>
          <ToastContainer></ToastContainer>
        </AuthProvider>
      </body>
    </html>
  );
}
